CPPFLAGS=-O3 -g

all: greedy bruteforce shuffle

greedy: greedy.cpp utils.hpp
	g++ $(CPPFLAGS) -o greedy greedy.cpp
bruteforce: bruteforce.cpp utils.hpp
	g++ $(CPPFLAGS) -o bruteforce bruteforce.cpp
shuffle: shuffle.cpp utils.hpp
	g++ $(CPPFLAGS) -o shuffle shuffle.cpp
